---
- name: Install bind9 and utils
  apt:
    name:
      - bind9
      - bind9utils
      - bind9-doc
    state: present
    update_cache: true

- name: Copy named.conf.options
  template:
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options
    owner: root
    group: bind
    mode: '0644'
  notify: restart bind9

- name: Copy named.conf.local
  template:
    src: named.conf.local.j2
    dest: /etc/bind/named.conf.local
    owner: root
    group: bind
    mode: '0644'
  notify: restart bind9

- name: Copy DNS zone file
  template:
    src: db.30.srs.adlin.j2
    dest: /etc/bind/db.{{ subdomain }}.srs.adlin
    owner: root
    group: bind
    mode: '0644'
  notify: restart bind9


